name: 8-bit
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - pytest
  - pytorch
  - torchaudio
  - torchvision
  - cudatoolkit=11.1
  - typer
  - ca-certificates
  - certifi
  - openssl
